(function () {
	window.Invaders = window.Invaders || {};

	var CANVAS_WIDTH = Invaders.CANVAS_WIDTH = 640;
	var CANVAS_HEIGHT = Invaders.CANVAS_HEIGHT = 640;
	var SPRITE_SHEET_SRC = Invaders.SPRITE_SHEET_SRC = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAEACAYAAAADRnAGAAACGUlEQVR42u3aSQ7CMBAEQIsn8P+/hiviAAK8zFIt5QbELiTHmfEYE3L9mZE9AAAAqAVwBQ8AAAD6THY5CgAAAKbfbPX3AQAAYBEEAADAuZrC6UUyfMEEAIBiAN8OePXnAQAAsLcmmKFPAQAAgHMbm+gbr3Sdo/LtcAAAANR6GywPAgBAM4D2JXAAABoBzBjA7AmlOx8AAEAzAOcDAADovTc4vQim6wUCABAYQG8QAADd4dPd2fRVYQAAANQG0B4HAABAawDnAwAA6AXgfAAAALpA2uMAAABwPgAAgPoAM9Ci/R4AAAD2dmqcEQIAIC/AiQGuAAYAAECcRS/a/cJXkUf2AAAAoBaA3iAAALrD+gIAAADY9baX/nwAAADNADwFAADo9YK0e5FMX/UFACA5QPSNEAAAAHKtCekmDAAAAADvBljtfgAAAGgMMGOrunvCy2uCAAAACFU6BwAAwF6AGQPa/XsAAADYB+B8AAAAtU+ItD4OAwAAAFVhAACaA0T7B44/BQAAANALwGMQAAAAADYO8If2+P31AgAAQN0SWbhFDwCAZlXgaO1xAAAA1FngnA8AACAeQPSNEAAAAM4CnC64AAAA4GzN4N9NSfgKEAAAAACszO26X8/X6BYAAAD0Anid8KcLAAAAAAAAAJBnwNEvAAAA9Jns1ygAAAAAAAAAAAAAAAAAAABAQ4COCENERERERERERBrnAa1sJuUVr3rsAAAAAElFTkSuQmCC';
	var LEFT_KEY = Invaders.LEFT_KEY = 37;
	var RIGHT_KEY = Invaders.RIGHT_KEY = 39;
	var SHOOT_KEY = Invaders.SHOOT_KEY = 32;
	var TEXT_BLINK_FREQ = Invaders.TEXT_BLINK_FREQ = 500;
	
	var ALIEN_BOTTOM_ROW = Invaders.ALIEN_BOTTOM_ROW = [{
	  x: 0,
	  y: 0,
	  w: 51,
	  h: 34
	}, {
	  x: 0,
	  y: 102,
	  w: 51,
	  h: 34
	}];
	var ALIEN_MIDDLE_ROW = Invaders.ALIEN_MIDDLE_ROW = [{
	  x: 0,
	  y: 137,
	  w: 50,
	  h: 33
	}, {
	  x: 0,
	  y: 170,
	  w: 50,
	  h: 34
	}];
	var ALIEN_TOP_ROW = Invaders.ALIEN_TOP_ROW = [{
	  x: 0,
	  y: 68,
	  w: 50,
	  h: 32
	}, {
	  x: 0,
	  y: 34,
	  w: 50,
	  h: 32
	}];
	var ALIEN_X_MARGIN = Invaders.ALIEN_X_MARGIN = 40;
	var ALIEN_SQUAD_WIDTH = Invaders.ALIEN_SQUAD_WIDTH = 11 * ALIEN_X_MARGIN;
})();